#!/usr/bin/env python3
"""
setup_voices.py — Interactive ElevenLabs voice picker for Prompt Island.

Fetches all voices available on your ElevenLabs account, lets you assign one
to each character, then writes the result to frontend/.env.local.

Usage:
    python scripts/setup_voices.py

Requires ELEVENLABS_API_KEY in your .env file (or as an environment variable).
No extra packages needed — uses only the standard library.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.request
import urllib.error
from pathlib import Path

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

CHARACTERS = [
    ("MACHIAVELLI", "Alex",   "Kalkulerende, glatt strateg"),
    ("CHAOS",       "Jordan", "Impulsiv, kaotisk energibombe"),
    ("EMPATH",      "Sam",    "Varm, emosjonell, relasjonsfokusert"),
    ("PEDANT",      "Morgan", "Presis, analytisk, korrekt"),
    ("PARANOID",    "Casey",  "Nervøs, mistenksom, paranoisk"),
    ("FLOATER",     "Riley",  "Ubestemt, tilpasningsdyktig"),
]

ENV_FILE   = Path(__file__).parent.parent / "frontend" / ".env.local"
DOTENV     = Path(__file__).parent.parent / ".env"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_api_key() -> str:
    """Read ELEVENLABS_API_KEY from .env or environment."""
    # Try environment first
    key = os.environ.get("ELEVENLABS_API_KEY", "").strip()
    if key:
        return key

    # Parse .env manually (no python-dotenv needed here)
    if DOTENV.exists():
        for line in DOTENV.read_text().splitlines():
            line = line.strip()
            if line.startswith("ELEVENLABS_API_KEY="):
                key = line.split("=", 1)[1].strip().strip('"').strip("'")
                if key:
                    return key

    return ""


def fetch_voices(api_key: str) -> list[dict]:
    """Return the list of voice dicts from the ElevenLabs /v1/voices endpoint."""
    req = urllib.request.Request(
        "https://api.elevenlabs.io/v1/voices",
        headers={"xi-api-key": api_key, "Accept": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        data = json.loads(resp.read())
    return data.get("voices", [])


def print_voices(voices: list[dict]) -> None:
    """Print numbered voice list with name, category, and ID."""
    print()
    print(f"  {'#':>3}  {'Name':<28}  {'Category':<18}  Voice ID")
    print(f"  {'─' * 3}  {'─' * 28}  {'─' * 18}  {'─' * 24}")
    for i, v in enumerate(voices, 1):
        name     = v.get("name", "?")[:28]
        category = v.get("category", "?")[:18]
        vid      = v.get("voice_id", "?")
        print(f"  {i:>3}  {name:<28}  {category:<18}  {vid}")
    print()


def pick_voice(voices: list[dict], char_key: str, display_name: str, description: str) -> str:
    """Prompt the user to pick a voice for one character. Returns the voice_id."""
    print(f"── {display_name} ({description}) ──────────────────────────")
    while True:
        raw = input(f"  Enter number or paste Voice ID for {display_name}: ").strip()
        if not raw:
            continue

        # Numeric selection
        if raw.isdigit():
            idx = int(raw) - 1
            if 0 <= idx < len(voices):
                chosen = voices[idx]
                vid = chosen["voice_id"]
                print(f"  ✓ {display_name} → {chosen['name']} ({vid})\n")
                return vid
            print(f"  ✗ Ugyldig nummer — velg mellom 1 og {len(voices)}")
            continue

        # Raw voice_id pasted in
        if len(raw) >= 10:
            print(f"  ✓ {display_name} → (custom ID) {raw}\n")
            return raw

        print("  ✗ Ikke gjenkjent — skriv nummeret fra listen eller lim inn en Voice ID.")


def write_env(assignments: dict[str, str]) -> None:
    """Write or update frontend/.env.local with the chosen voice IDs."""
    existing: dict[str, str] = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()

    # Merge assignments
    existing.setdefault("NEXT_PUBLIC_API_WS_URL",  "ws://localhost:8000/ws")
    existing.setdefault("NEXT_PUBLIC_API_HTTP_URL", "http://localhost:8000")
    existing.update(assignments)

    lines = [
        "# Prompt Island Frontend — generated by scripts/setup_voices.py",
        "",
        f"NEXT_PUBLIC_API_WS_URL={existing.pop('NEXT_PUBLIC_API_WS_URL')}",
        f"NEXT_PUBLIC_API_HTTP_URL={existing.pop('NEXT_PUBLIC_API_HTTP_URL')}",
        "",
        "# ElevenLabs",
    ]

    if "NEXT_PUBLIC_ELEVENLABS_API_KEY" in existing:
        lines.append(f"NEXT_PUBLIC_ELEVENLABS_API_KEY={existing.pop('NEXT_PUBLIC_ELEVENLABS_API_KEY')}")

    lines.append("")
    for char_key, _, _ in CHARACTERS:
        env_key = f"NEXT_PUBLIC_VOICE_{char_key}"
        if env_key in existing:
            lines.append(f"{env_key}={existing.pop(env_key)}")

    # Any remaining keys
    if existing:
        lines.append("")
        for k, v in existing.items():
            lines.append(f"{k}={v}")

    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    ENV_FILE.write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print("\n╔══════════════════════════════════════════════╗")
    print("║   Prompt Island — ElevenLabs Voice Setup    ║")
    print("╚══════════════════════════════════════════════╝\n")

    # 1. API key
    api_key = load_api_key()
    if not api_key:
        api_key = input("Lim inn ELEVENLABS_API_KEY: ").strip()
    if not api_key:
        print("✗ Ingen API-nøkkel — avslutter.")
        sys.exit(1)

    # 2. Fetch voices
    print("Henter stemmer fra ElevenLabs…")
    try:
        voices = fetch_voices(api_key)
    except urllib.error.HTTPError as e:
        print(f"✗ API-feil {e.code}: {e.reason}")
        if e.code == 401:
            print("  Sjekk at ELEVENLABS_API_KEY er korrekt.")
        sys.exit(1)
    except Exception as e:
        print(f"✗ Nettverksfeil: {e}")
        sys.exit(1)

    if not voices:
        print("✗ Ingen stemmer funnet på kontoen.")
        sys.exit(1)

    print(f"  Fant {len(voices)} stemme(r).\n")
    print_voices(voices)

    # 3. Pick a voice per character
    assignments: dict[str, str] = {
        "NEXT_PUBLIC_ELEVENLABS_API_KEY": api_key,
    }

    print("Velg én stemme per karakter (skriv nummeret fra listen over):\n")
    for char_key, display_name, description in CHARACTERS:
        vid = pick_voice(voices, char_key, display_name, description)
        assignments[f"NEXT_PUBLIC_VOICE_{char_key}"] = vid

    # 4. Write frontend/.env.local
    write_env(assignments)

    print(f"\n✓ Skrevet til {ENV_FILE.relative_to(Path.cwd())}")
    print("  Start frontenden med:  cd frontend && npm run dev\n")


if __name__ == "__main__":
    main()
